---
#=================================
#{player}-      ชื่อในเกม (name in game) <<<<<<<
#{group} -      ยศ (group) <<<<<<<
#{faction} -    แคลน (factions) <<<<<<<
#{money} -      เงิน (money) <<<<<<<
#{gm} -         เกมโหมด (gamemode) <<<<<<
#{IP} -         ip ของผู้เล่น (ip address) <<<<<<<
#{online} -     จำนวนที่ออนไลน์ (players) <<<<<<
#{max_online} - max ออนไลน์ (max players) <<<<<<<
#{hp} -         สถานะสุขภาพ (health) <<<<<<<
#{maxhp} -      max สุขภาพ (max health) <<<<<<<
#{X}/{Y}/{Z} -  พิกัด (position xyz) <<<<<<<
#{level} -      ชื่อโลก (world name) <<<<<<<
#{time} -       เวลา (time) <<<<<<<
#{id}:{ids} -   ID item (id item) <<<<<<<
#{item} -       ชื่อ item (name item) <<<<<<<
#{tps} -        TPS เซิร์ฟเวอร์ (current tps) <<<<<<<
#{usage}-       USAGE เซิร์ฟเวอร์ (server usage) <<<<<<<
#{tag} -        บนหัว (name tag) <<<<<<<
#{kill} -       จำนวนฆาตกรรมทั้งหมด (kills) <<<<<<<
#{deaths} -     ตายรวม (deaths) <<<<<<<
#{R1} -         สุ่มสีข้อความ มี{R1}ถึง{R23} (random colors have {R1} - {R23}) <<<<<<
#{h} -          บาร์ทำให้ชิดขวา[ใส่ทุกครั้งที่ใช้ \n ] (make bar right) <<<<<<
#{n} -          ยกบาร์ขึ้น (raise the bar) <<<<<<
#\n -           ขึ้นบรรทัดใหม่ (new line) <<<<<<<<

#=================================

bar: "{h}§l§7(§cMC§f-§6Car§erot§aCraft§bP§dE§f)§r\n{h}§l§a»§eสวัสดี§b: §c{R4}{player}§r\n{h}§l§a»§eยศ§b: {R3}{group}§r\n{h}§l§a»§eออนไลน์§b: §a{onl}§8/§c{monl}§r\n{h}§l§a»§eเงิน§b: §6{money}§r\n{h}§l§a»§eแคลน§b: §f{faction}§r\n{h}§l§a»§eItem§b: {R2}{item}§r\n{h}§l§a»§eID§b: {R1}{id}:{ids}§r\n§r{h}§l§a»§eฆ่า§b: §c{kill}§r\n{h}§l§a»§eตาย§b: §c{deaths}{n}"

#=================================
...
